//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.MailBoxService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailBoxService.IGateway")]
    public interface IGateway {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateway/SendMail", ReplyAction="http://tempuri.org/IGateway/SendMailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MailBoxModels.Gateway.EmailRequestFault), Action="http://tempuri.org/IGateway/SendMailEmailRequestFaultFault", Name="EmailRequestFault", Namespace="http://schemas.datacontract.org/2004/07/MailBoxModels.Gateway")]
        void SendMail(MailBoxModels.Gateway.EmailRequest msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateway/SendTemplateMail", ReplyAction="http://tempuri.org/IGateway/SendTemplateMailResponse")]
        void SendTemplateMail(MailBoxModels.Gateway.EmailRequest req, MailBoxModels.EmailTemplatesModels.SimpleTemplate templateData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGatewayChannel : TestClient.MailBoxService.IGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayClient : System.ServiceModel.ClientBase<TestClient.MailBoxService.IGateway>, TestClient.MailBoxService.IGateway {
        
        public GatewayClient() {
        }
        
        public GatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMail(MailBoxModels.Gateway.EmailRequest msg) {
            base.Channel.SendMail(msg);
        }
        
        public void SendTemplateMail(MailBoxModels.Gateway.EmailRequest req, MailBoxModels.EmailTemplatesModels.SimpleTemplate templateData) {
            base.Channel.SendTemplateMail(req, templateData);
        }
    }
}
